
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri May 05 21:18:59 CEST 2023
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int FOUG = 22;
  public static final int RETOUR = 23;
  public static final int PUNTOCOMA = 42;
  public static final int REF = 4;
  public static final int WRITE = 44;
  public static final int IGUAL = 16;
  public static final int OU = 19;
  public static final int TDEF = 27;
  public static final int BOOL = 31;
  public static final int TBOOL = 30;
  public static final int CLASS = 26;
  public static final int DIV = 9;
  public static final int NUM = 29;
  public static final int IF = 20;
  public static final int THIS = 6;
  public static final int APAREN = 33;
  public static final int DIST = 14;
  public static final int EOF = 0;
  public static final int ACORCH = 37;
  public static final int ASIG = 17;
  public static final int AST = 3;
  public static final int CPAREN = 34;
  public static final int CCORCH = 38;
  public static final int error = 1;
  public static final int COMA = 39;
  public static final int MENOS = 8;
  public static final int MENOR = 12;
  public static final int MOD = 10;
  public static final int ET = 18;
  public static final int ALLAVE = 35;
  public static final int CLLAVE = 36;
  public static final int NULE = 32;
  public static final int MAYOR = 11;
  public static final int TINT = 28;
  public static final int ELSE = 21;
  public static final int PUNTO = 41;
  public static final int MAYORIG = 13;
  public static final int READ = 43;
  public static final int IDEN = 2;
  public static final int WHILE = 24;
  public static final int MENORIG = 15;
  public static final int DPUNTOS = 40;
  public static final int ALM = 5;
  public static final int STRUCT = 25;
  public static final int MAS = 7;
}

